### ISSUE TITLE
Babel-Polyfill needed for async/await support

### ISSUE THREAD

**Issue by Dardin-dale** [mmick66/electrate#16]
using node-serialport with this boilerplate and I needed to use async/await. I ran into an error that regeneratorRuntime was not defined. Adding the babel-polyfill dependency and importing it into both main.js and index.js allows for async/await on both the main and renderer processes respectively.

**Comment by mmick66** [comment]
Could you please help me by adding a pull request?

**Comment by Dardin-dale** [comment]
sure thing!

**Comment by mmick66** [comment]
Thanks!
