### ISSUE TITLE
Move to gulp 4.0.0

### ISSUE THREAD

**Issue by svoboda-rabstvo** [mmick66/electrate#4]
Please, update `gulpfile` to gulp 4.0.0. 
Because by default install gulp 4.0.0 and I need to change all series tasks of gulp. 
Thanks :)

**Comment by mmick66** [comment]
Could you help me with a pull request please?

**Comment by svoboda-rabstvo** [comment]
@mmick66 Yes, of course

**Comment by Xstoudi** [comment]
Still waiting for it :cry:

**Comment by mmick66** [comment]
I am a little busy right now, can one of you guys help me by doing a pull request?

**Comment by mmick66** [comment]
I tagged it as “help needed” for a reason :)

**Comment by svoboda-rabstvo** [comment]
I'm created PR. You can look it :)  #5

**Comment by mmick66** [comment]
Thanks!! Merged!
