### ISSUE TITLE
Babel is not up to date and index path is different from your documentation

### ISSUE THREAD

**Issue by MarvinCourcier** [mmick66/electrate#7]
Hello mmick66,

First of all thank you for your tutorial.
I'm just writing here that it has been really helpful in setting up my Electron project with React.
However:
1 - Your documentation on Medium is not following what you did on your project which will mislead a lot of people just like it did with me.
2 - Your way of using babel doesn't work anymore. So you should update your project as well as your Medium article.

After digging through your work and spending a lot of time debugging, I've successfully updated your work so it can be functional for my own project.

**Comment by mmick66** [comment]
Thank you very much. I am sorry to hear you had to spend so much time, but since you did, would you mind adding the changes in a pull request? Thanks!

**Comment by mmick66** [comment]
I have fixed the discrepancy. Thank you for the notes.
