### ISSUE TITLE
Image isn't loaded when electron-builder is used.

### ISSUE THREAD

**Issue by JCraigWasTaken** [mmick66/electrate#9]
Hello,

I have been trying to create a packaged release version of this repo and logo.png isn't being loaded properly (Failed to load resource: net::ERR_FILE_NOT_FOUND) . I think the path to the image is somehow being broken when electron-builder packages the project. The project runs fine when I run it using npm run.

Other people have had the same issue with the boilerplate:

https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/250#issuecomment-227494838

Have you experienced this issue and if so do you have a workaround?

**Comment by karthick-t2s** [comment]
How did you resolve?
